
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

#spring.application.name=poslasticarnica

spring.datasource.url=jdbc:mysql://localhost:3308/poslasticarnica?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Hibernate postavke
#automatski kreira/menja tabele prema entitetima (create, update, validate, none...)
spring.jpa.hibernate.ddl-auto=update
#prikazuje SQL upite u konzoli
spring.jpa.show-sql=true
#formatira SQL da bude citljiv u izlazu
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect